/**
 * event crud operation names or something
 */
export const EVENT_ACTIONS = {
  CREATE: "CREATE_EVENT",
  CREATE_SUCCESS: "CREATE_EVENT_SUCCESS",
  GET_ALL: "GET_EVENTS",
  GET_ALL_SUCCESS: "GET_EVENTS_SUCCESS",
  DELETE: "DELETE_EVENTS",
  DELETE_SUCCESS: "DELETE_EVENTS_SUCCESS"
};
export const COUNTRY_ACTIONS = {
  CREATE: "CREATE_COUNTRY",

  GET_ALL: "GET_COUNTRIES",
  GET_ALL_SUCCESS: "GET_COUNTRIES_SUCCESS",  
  GET_ALL_FAIL: "GET_COUNTRIES_FAIL",  

  GET_ONE: "GET_ONE_COUNTRY",  
  GET_ONE_SUCCESS: "GET_ONE_COUNTRY_SUCCESS",  
  GET_ONE_FAIL: "GET_ONE_COUNTRY_FAIL",  

};

export const NEWS_SOURCE_ACTIONS = {
  GET_ALL: "GET_ALL_NEWS_SOURCES",
  GET_ALL_SUCCESS: "GET_ALL_NEWS_SOURCES_SUCCESS",
  GET_ALL_FAIL: "GET_ALL_NEWS_SOURCES_FAIL",

  CREATE: "CREATE_NEWS_SOURCE",
  CREATE_SUCCESS: "CREATE_NEWS_SOURCE_SUCCESS",
  CREATE_FAIL: "CREATE_NEWS_SOURCE_FAIL",
};

export const ARTICLE_ACTIONS = {
  GET_ALL: "GET_ARTICLES",
  GET_ALL_SUCCESS: "GET_ARTICLES_SUCCESS",
  GET_ALL_FAIL: "GET_ARTICLES_FAIL",
};

export const ERROR_ACTIONS = {
  GET: "GET_ERRORS"
};

export const MESSAGE_ACTIONS = {
  GET_ALL: "GET_ALL_MESSAGES",
  CREATE_MESSAGE: "CREATE_MESSAGE"
};

export const USER_ACTIONS = {
  LOADING: "USER_LOADING",
  LOADED: "USER_LOADED",
  AUTH_ERROR: "USER_AUTH_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
};