/**
 * lead crud operation names or something
 */
export const LEAD_ACTIONS = {
  CREATE: "CREATE_LEAD",
  GET_ALL: "GET_LEADS",
  DELETE: "DELETE_LEADS"
};

export const ERROR_ACTIONS = {
  GET: "GET_ERRORS"
};

export const MESSAGE_ACTIONS = {
  GET_ALL: "GET_ALL_MESSAGES",
  CREATE_MESSAGE: "CREATE_MESSAGE"
};

export const USER_ACTIONS = {
  LOADING: "USER_LOADING",
  LOADED: "USER_LOADED",
  AUTH_ERROR: "USER_AUTH_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
};